name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§¾ Checkout code
        uses: actions/checkout@v3

      - name: ðŸ”§ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ðŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ðŸš€ Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: root
          SERVER_IP: 78.24.180.133
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          bash -c "
            ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP '
              set -e
              cd ~/portfolio
              echo \"ðŸ“¥ Pulling latest code...\"
              git fetch --all
              git reset --hard origin/main

              echo \"ðŸ›‘ Stopping old container...\"
              yarn prod:down || true

              echo \"ðŸ“¦ Installing deps...\"
              yarn install --frozen-lockfile

              echo \"ðŸš€ Starting container...\"
              yarn prod:up
            '
          "

          rm -f private_key.pem
